kaizentm/gitops-manifests

azure-vote-manifests/gen_manifests.yaml
azure-vote-manifests/hld/helm/.helmignore
azure-vote-manifests/hld/helm/Chart.yaml
azure-vote-manifests/hld/helm/templates/az-vote-back-deployment.yaml
azure-vote-manifests/hld/helm/templates/az-vote-back-svc.yaml
azure-vote-manifests/hld/helm/templates/az-vote-front-deployment.yaml
azure-vote-manifests/hld/helm/templates/az-vote-front-ingress.yaml
azure-vote-manifests/hld/helm/templates/az-vote-loadbalancer-svc.yaml
azure-vote-manifests/hld/helm/values.yaml
azure-vote-manifests/hld/kustomize/base/kustomization.yaml

deployment 597399284

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml

deployment 597789302

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 597814789

---

azure-vote-manifests/hld/helm/templates/az-vote-front-ingress.yaml
azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 597884793

---

azure-vote-manifests/hld/helm/templates/az-vote-front-ingress.yaml
azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 597969720

---

azure-vote-manifests/hld/helm/.helmignore
azure-vote-manifests/hld/helm/Chart.yaml
azure-vote-manifests/hld/helm/templates/az-vote-back-deployment.yaml
azure-vote-manifests/hld/helm/templates/az-vote-back-svc.yaml
azure-vote-manifests/hld/helm/templates/az-vote-front-deployment.yaml
azure-vote-manifests/hld/helm/templates/az-vote-front-ingress.yaml
azure-vote-manifests/hld/helm/templates/az-vote-loadbalancer-svc.yaml
azure-vote-manifests/hld/helm/values.yaml
azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 600322891

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 600322035

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 601459872

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 601555245

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 601589115

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 601605201

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 611388698

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 611674006

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 611718425

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 611743579

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 611767548

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 615180089

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 615209181

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 619162279

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 619178117

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 720665692

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 720871497

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 723999996

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 745427698

---

azure-vote-manifests/hld/kustomize/base/kustomization.yaml
azure-vote-manifests/manifest/gen_manifests.yaml

deployment 745441743

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/configMap.yaml
gitops-connector/hld/helm/templates/deployment.yaml
gitops-connector/hld/helm/templates/secret.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 836604498

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/secret.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 836642479

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 837295403

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 837208914

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/configMap.yaml
gitops-connector/hld/helm/templates/deployment.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 840916162

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 840938234

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 840959467

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/service.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 840979145

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 843396132

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/deployment.yaml
gitops-connector/hld/helm/templates/subscribers.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 843565533

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 843585963

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 843701677

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/deployment.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 876100922

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/templates/deployment.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 876140151

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/README.md
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 879352361

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 880146969

---

gitops-connector/hld/helm/Chart.yaml
gitops-connector/hld/helm/values.yaml
gitops-connector/manifest/gen_manifests.yaml

deployment 920023090

---

azure-vote/hld/helm/Chart.yaml
azure-vote/hld/helm/templates/az-vote-back-deployment.yaml
azure-vote/hld/helm/templates/az-vote-back-svc.yaml
azure-vote/hld/helm/templates/az-vote-front-deployment.yaml
azure-vote/hld/helm/templates/az-vote-front-ingress.yaml
azure-vote/hld/helm/templates/az-vote-loadbalancer-svc.yaml
azure-vote/hld/helm/values.yaml
azure-vote/hld/kustomize/base/kustomization.yaml
azure-vote/manifest/gen_manifests.yaml

deployment '958756064'

---

azure-vote/hld/helm/values.yaml
azure-vote/hld/kustomize/base/kustomization.yaml
azure-vote/manifest/gen_manifests.yaml

deployment '958780009'

---

azure-vote/hld/azure-vote-back/helm/.helmignore
azure-vote/hld/azure-vote-back/helm/Chart.yaml
azure-vote/hld/azure-vote-back/helm/templates/az-vote-back-deployment.yaml
azure-vote/hld/azure-vote-back/helm/templates/az-vote-back-svc.yaml
azure-vote/hld/azure-vote-back/helm/values.yaml
azure-vote/hld/azure-vote-back/kustomize/base/kustomization.yaml
azure-vote/hld/azure-vote-front/helm/.helmignore
azure-vote/hld/azure-vote-front/helm/Chart.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-front-deployment.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-front-ingress.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-loadbalancer-svc.yaml
azure-vote/hld/azure-vote-front/helm/values.yaml
azure-vote/hld/azure-vote-front/kustomize/base/kustomization.yaml
azure-vote/manifest/gen_manifests.yaml

deployment '961858172'

---

azure-vote/hld/azure-vote-back/helm/.helmignore
azure-vote/hld/azure-vote-back/helm/Chart.yaml
azure-vote/hld/azure-vote-back/helm/templates/az-vote-back-deployment.yaml
azure-vote/hld/azure-vote-back/helm/templates/az-vote-back-svc.yaml
azure-vote/hld/azure-vote-back/helm/values.yaml
azure-vote/hld/azure-vote-back/kustomize/base/kustomization.yaml
azure-vote/hld/azure-vote-front/helm/.helmignore
azure-vote/hld/azure-vote-front/helm/Chart.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-front-deployment.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-front-ingress.yaml
azure-vote/hld/azure-vote-front/helm/templates/az-vote-loadbalancer-svc.yaml
azure-vote/hld/azure-vote-front/helm/values.yaml
azure-vote/hld/azure-vote-front/kustomize/base/kustomization.yaml
azure-vote/manifest/gen_manifests.yaml

deployment '961875377'

---

azure-vote/hld/azure-vote-back/kustomize/base/kustomization.yaml
azure-vote/hld/azure-vote-front/kustomize/base/kustomization.yaml

deployment '980283121'
